application:
  name: redis
  createNamespace: ###ZARF_VAR_REDIS_CREATE_NAMESPACE###
  namespace: redis
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/packages/redis.git
  ref:
    # renovate: datasource=gitlab-tags depName=big-bang/product/packages/redis versioning=loose registryUrl=https://repo1.dso.mil
    tag: 18.0.4-bb.0
  dependsOn:
    ###ZARF_VAR_REDIS_DEPENDS_ON###
  baseValues:
    hostname: ###ZARF_VAR_DOMAIN###
    istio:
      enabled: false
      redis:
        enabled: false
    auth:
      enabled: false
    sentinel:
      enabled: true
      image:
        pullPolicy: Always
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 256Mi
    networkPolicy:
      enabled: true
      ingressNSMatchLabels:
        kubernetes.io/metadata.name: ###ZARF_VAR_NETPOL_ALLOW_NS###
      ingressNSPodMatchLabels:
        release:  ###ZARF_VAR_NETPOL_ALLOW_NS###
