apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: ###ZARF_VAR_APP###-redis-external-names-exception
  namespace: ###ZARF_VAR_APP###
spec:
  exceptions:
  - policyName: restrict-external-names
    ruleNames:
    - external-names
  match:
    any:
    - resources:
        kinds:
        - Service
        namespaces:
        - ###ZARF_VAR_APP###
        names:
        - ###ZARF_VAR_APP###-redis
