apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: redis-registry-exception
  namespace: redis
spec:
  exceptions:
  - policyName: restrict-image-registries
    ruleNames:
    - validate-registries
    - autogen-validate-registries
  match:
    any:
    - resources:
        kinds:
        - StatefulSet
        namespaces:
        - redis
